import { ArrowLeft, CheckCircle2, Pencil, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTasks } from '../context/TaskContext';
import { useState } from 'react';

export default function TaskDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const { tasks, deleteTask, toggleComplete, updateTask } = useTasks();
  const task = tasks.find((item) => item.id === id);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(() => task ? { title: task.title, description: task.description, priority: task.priority, category: task.category, dueDate: task.dueDate } : null);
  if (!task) return <main className="task-page"><Link className="back-link" to="/tasks"><ArrowLeft size={14} /> BACK</Link><div className="empty-state">TASK NOT FOUND.</div></main>;
  function saveEdit() { updateTask(task.id, draft); setEditing(false); }
  return <main className="task-page narrow-page"><Link className="back-link" to="/tasks"><ArrowLeft size={14} /> BACK TO TASKS</Link><article className="detail-card"><div className="mini-label">TASK DETAILS / {task.status.toUpperCase()}</div>{editing ? <div className="task-form inline-edit"><label>Task Header<input value={draft.title} onChange={(e) => setDraft({ ...draft, title:e.target.value })} /></label><label>Description<textarea rows={5} value={draft.description} onChange={(e) => setDraft({ ...draft, description:e.target.value })} /></label><div className="form-two"><label>Priority<select value={draft.priority} onChange={(e) => setDraft({ ...draft, priority:e.target.value })}><option>High</option><option>Medium</option><option>Low</option></select></label><label>Category<select value={draft.category} onChange={(e) => setDraft({ ...draft, category:e.target.value })}><option>Academic</option><option>Personal</option></select></label></div><label>Due Date<input type="date" value={draft.dueDate} onChange={(e) => setDraft({ ...draft, dueDate:e.target.value })} /></label><div className="detail-actions"><button className="primary-link" onClick={saveEdit}>SAVE CHANGES</button><button className="secondary-link" onClick={() => setEditing(false)}>CANCEL</button></div></div> : <><h1>{task.title}</h1><p>{task.description || 'No description provided.'}</p><div className="detail-grid"><span>PRIORITY<strong>{task.priority}</strong></span><span>CATEGORY<strong>{task.category}</strong></span><span>RAISED<strong>{new Date(task.raisedAt).toLocaleString()}</strong></span><span>DUE<strong>{task.dueDate || '—'}</strong></span></div><div className="detail-actions"><button className="primary-link" onClick={() => toggleComplete(task.id)}><CheckCircle2 size={15} /> {task.status === 'Closed' ? 'REOPEN' : 'COMPLETE'}</button><button className="danger-link" onClick={() => { deleteTask(task.id); navigate('/tasks'); }}><Trash2 size={15} /> DELETE</button><button className="secondary-link" onClick={() => setEditing(true)}><Pencil size={15} /> EDIT</button></div></>}</article></main>;
}
