import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { PackageCheck, ArrowRight, XCircle, MapPin, CalendarDays, CreditCard, ChevronDown, ChevronUp, ShoppingBag, ReceiptText, Truck } from 'lucide-react';
import { useShop } from '../context/ShopContext';
import { getProductImage } from '../utils/productImage';
const reasons=['Changed my mind','Ordered by mistake','Found a better price','Delivery is taking too long','Product no longer needed','Other'];
export default function OrdersPage(){
 const {state,dispatch}=useShop(); const navigate=useNavigate(); const [open,setOpen]=useState(state.orders[0]?.id||null); const [cancelId,setCancelId]=useState(null); const [reason,setReason]=useState(reasons[0]); 
 if(!state.orders.length)return <main className="page-width empty-cart"><PackageCheck size={62}/><h1>Track your orders</h1><p>Your placed orders will appear here with items, status and cancellation controls.</p><Link to="/" className="primary-btn">Continue shopping <ArrowRight size={17}/></Link></main>;
 return <main className="page-width orders-page"><div className="page-heading"><span>YOUR ORDERS</span><h1>Track your orders <small>{state.orders.length} order{state.orders.length>1?'s':''}</small></h1></div><div className="orders-list">{state.orders.map(order=><article className="order-card" key={order.id}><button className="order-head" onClick={()=>setOpen(open===order.id?null:order.id)}><div><b>#{order.id}</b><span><CalendarDays size={13}/> {new Date(order.placedAt).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</span></div><div className={`order-status ${order.status.toLowerCase()}`}>{order.status}</div>{open===order.id?<ChevronUp/>:<ChevronDown/>}</button>{open===order.id&&<div className="order-body">
   <div className="order-summary-strip"><div><PackageCheck/><span>Status</span><b>{order.status}</b></div><div><Truck/><span>Delivery</span><b>{order.status==='Cancelled'?'Cancelled':'2–4 business days'}</b></div><div><ReceiptText/><span>Order total</span><b>₹{order.total.toLocaleString('en-IN')}</b></div></div>
   <h3 className="order-section-label">Items ordered</h3><div className="order-items">{order.items.map(item=><button className="order-item" key={item.id} onClick={()=>navigate(`/product/${item.id}`)}><img src={getProductImage(item)} alt=""/><div><b>{item.title}</b><span>{item.brand||'VIVA'} · Qty {item.qty}</span><strong>₹{(item.price*item.qty).toLocaleString('en-IN')}</strong><small>View product →</small></div></button>)}</div>
   <div className="order-details-grid"><div><MapPin/><span>Delivery address</span><b>{order.address.name}<br/>{order.address.line1}, {order.address.city}, {order.address.state} — {order.address.pincode}<br/>Phone: {order.address.phone}</b></div><div><CreditCard/><span>Payment</span><b>{order.paymentMethod}</b></div><div><ReceiptText/><span>Price details</span><b>Subtotal ₹{order.subtotal.toLocaleString('en-IN')}<br/>Discount − ₹{order.discount.toLocaleString('en-IN')}<br/>GST ₹{order.gst.toLocaleString('en-IN')}<br/>Shipping {order.shipping?'₹'+order.shipping:'FREE'}</b></div></div>
   {order.status!=='Cancelled'&&<div className="order-actions"><button className="cancel-btn" onClick={()=>{setCancelId(order.id);setReason(reasons[0])}}><XCircle size={16}/> Cancel order</button></div>}
   {order.status==='Cancelled'&&<div className="cancelled-note"><XCircle size={16}/> Cancelled: {order.cancellationReason} · {new Date(order.cancelledAt).toLocaleDateString('en-IN')}</div>}
   {cancelId===order.id&&<div className="cancel-panel"><h3>Why are you cancelling this order?</h3><p>Please select a reason to continue.</p><select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(r=><option key={r}>{r}</option>)}</select><div><button className="ghost-btn" onClick={()=>setCancelId(null)}>Keep order</button><button className="cancel-confirm" onClick={()=>{dispatch({type:'CANCEL_ORDER',id:order.id,reason});setCancelId(null)}}>Confirm cancellation</button></div></div>}
  </div>}</article>)}</div></main>;
}
